Campus-Compass-SOEN-390/Watermelons_SOEN390

- coverage/lcov-report/base.css
- coverage/lcov-report/sorter.js
fixed some major code smells, as recommended by sonarqube
- Changed var to let for codecov
- changed the ternary operator in `sorter.js ` due to readability, and understanding issues.
> Added some linting fixes to fix some coding violations

- myApp/app/__tests__/OutdoorMapSwitcher.test.js
unit test for outdoor map switcher
> Unit tests for map switcher

- myApp/app/components/StartAndDestinationPoints.tsx
- myApp/app/styles/StartAndDestinationPointsStyles.js
- myApp/package-lock.json
- myApp/package.json
- myApp/yarn.lock
New features
- Current location is displayed as one of the drop down menu options as "My Location"
- Design corresponds to the prototype
Tests
- Feature tested on Expo mobile app
- Current location is accurately fetched
- Feature works on android emulator
closes #30 #89
> User can successfully select his current location as a starting point

- myApp/app/(tabs)/interest-points.jsx
the "Get directions" button has been added to the interest points. It is ready to be linked to the routing. Closes #135, #134
> UI "Get directions" button added on interest points

- myApp/app/__tests__/HomePage.tests.js
- myApp/app/api/shuttleLiveData.js
- myApp/app/api/shuttleSchedule.js
- myApp/app/api/shuttleScheduleData.js
- myApp/app/screens/HomePage.js
- myApp/app/screens/ShuttleScheduleScreen.js
- myApp/package-lock.json
- myApp/package.json
- myApp/yarn.lock
https://github.com/user-attachments/assets/4363f3fe-a171-4ce8-a4a0-eb55d842a7e3
> build Shuttle Bus Schedule Button + fix terminal warnings

- myApp/app/__tests__/StartAndDestinationPoints.tests.js
- myApp/app/components/StartAndDestinationPoints.tsx
- myApp/app/styles/StartAndDestinationPointsStyles.js
- Refactored the implementation of the mode of transportation buttons
- Added styling to the selected mode of transportation
- Added unit tests for the mode of transportation buttons
> Refactored and added styling to transportation buttons

- myApp/app/(tabs)/indoor-map.jsx
- myApp/app/__tests__/IndoorMap.test.tsx
- myApp/app/screens/IndoorMapPage.js
- myApp/app/styles/IndoorMapStyles.js
- myApp/app/styles/OutdoorMapStyles.js
- myApp/jest.setup.js
- Added buttons to move floors (up and down)
- Current floor text is a placeholder 
- Added button to switch building within the campus
- Current building names are placeholders
- Added button to switch campus
> Added indoor navigation buttons

- myApp/app/api/buildingData.ts
- Added highlight to the Hall Building
> Added highlight to Hall Building

- myApp/android/app/src/main/AndroidManifest.xml
- myApp/android/build.gradle
- myApp/android/gradle.properties
- myApp/app/(tabs)/map.jsx
- myApp/package-lock.json
This pull request includes changes to integrate Mapbox and Google Maps API keys into the Android application. The changes include adding the Mapbox Maven repository, configuring the Google Maps API key, and setting the Mapbox downloads token.
Integration of Mapbox and Google Maps:
* [`myApp/android/app/src/main/AndroidManifest.xml`](diffhunk://#diff-f3a8d1b625d9da3cac3316273a574e39b5fe707f64c650d1b3256faa60daa314R17): Added the Google Maps API key to the application metadata.
* [`myApp/android/build.gradle`](diffhunk://#diff-f18b22011945af16dca33914658b315de5c206394444aca074ad485d7a551b55R40-R50): Added the Mapbox Maven repository with authentication credentials.
* [`myApp/android/gradle.properties`](diffhunk://#diff-f19d77fe44bbe16a6b41b4f2b27c7bc67e737637034fcad6d0fdf4ae903d8f44R57-R58): …
> Mapbox android

- myApp/app/(tabs)/map.jsx
When clicking on loyola campus on Homepage, user is redirected to the correct campus
> Fix for bug-182

- myApp/app/__tests__/IndoorMapTests/FloorNavigation.tests.js
- myApp/app/__tests__/IndoorMapTests/IndoorMap.tests.js
- myApp/app/__tests__/IndoorMapTests/IndoorMapContext.tests.js
- myApp/app/__tests__/IndoorMapTests/IndoorMaputils.tests.js
- myApp/app/__tests__/IndoorMapTests/MapDirections.tests.js
Added unit tests for the following files/components:
- IndoorMap
- IndoorMapContext
- IndoorMapUtils
- MapDirections
- FloorNavigation
> Unit tests for indoor map

- myApp/app/__tests__/HomePage.tests.js
HomePage.test was missing a test case to test interest-point button
> Unit test for interest point button on Homepage

- myApp/app/(tabs)/map.jsx
- myApp/app/__tests__/StartAndDestinationPoints.tests.js
- myApp/app/components/StartAndDestinationPoints.tsx
- myApp/app/styles/StartAndDestinationPointsStyles.js
ETA and Cancel Buttons added to the Footer. Unit test modified to take it into account.
-Given Footer is visible
-When the X Button is pressed
-Then footer not visible anymore
-Given Footer is visible
-When a mode of transportation is selected
-Then the footer also displays the ETA
Closes #236
> ETA + Cancel Buttons added to the Footer

- myApp/app/__tests__/IndoorMapTests/MapDirections.tests.js
- myApp/app/components/MapDirections.tsx
-No longer fetch routes with mapbox
-Fetch with google maps to be consistent with steps, and ETA
-Also fetch alternatives and display them transparently as opposed to the fastest route that is displayed as a solid colour
-Adjusted existing unit tests
-Manual tests with different origin and destination points
-This will likely help Uyi with #242
> Fetch maps with google rather than mapbox + fetch alternatives too

- myApp/app/(tabs)/interest-points.jsx
- myApp/app/(tabs)/map.jsx
- myApp/app/__tests__/IndoorMapTests/IndoorMap.tests.js
- myApp/app/api/POIDataSubject.js
- myApp/app/api/poiApi.js
- myApp/app/components/POI/FilterModal.js
- myApp/app/context/LocationContext.tsx
- myApp/app/styles/poiStyles.js
- myApp/app/utils/shuttleUtils.js
Implementation of the Observer pattern for managing Points of Interest (POI) data. The main changes include the addition of a new `POIDataSubject` class, updates to the `fetchPOIData` function, and modifications to the `InterestPoints` and `MapView` components to subscribe to POI data changes.
* **`myApp/app/api/POIDataSubject.js`**: Added a new `POIDataSubject` class that implements the Observable/Subject pattern for POI data, allowing components to subscribe to data updates and be notified when data changes.
* **`myApp/app/api/poiApi.js`**: Modified the `fetchPOIData` function to integrate with the Observer pattern by setting the loading state and updating the subject with new data. Added the `updatePOICache` function to notify observers of data changes. …
> Implement POIDataSubject for Observer pattern and integrate with POI and map

- myApp/Maestro/POI.yml
- myApp/Maestro/homePage.yaml
- myApp/app/components/POI/FilterModal.js
- Home page
test all buttons
updated to account for new button names and test IDs, as well as removed button 
https://github.com/Campus-Compass-SOEN-390/Watermelons_SOEN390/issues/275
- Points of Interest 
Added IDs for components and buttons to make the test more reliable across different devices 
Enhanced overall test 
https://github.com/Campus-Compass-SOEN-390/Watermelons_SOEN390/issues/224
This PR depends on https://github.com/Campus-Compass-SOEN-390/Watermelons_SOEN390/pull/269
Do not merge before #269 is merged
> Updated Maestro tests for Home page and POi

- myApp/app/(tabs)/map.jsx
- myApp/app/__tests__/CalendarFetching.test.js
- myApp/app/__tests__/MonthPicket.test.js
- myApp/app/components/MonthPicker.js
- myApp/app/screens/CalendarFetching.js
- myApp/app/screens/HomePage.js
- myApp/app/styles/CalendarFetchingStyles.js
- myApp/app/styles/GoogleScheduleStyles.js
- myApp/app/styles/HomePageStyles.js
- myApp/app/styles/InterestPointsStyles.js
- myApp/app/styles/OutdoorMapStyles.js
- myApp/app/styles/POIListStyle.js
- myApp/app/styles/StartAndDestinationPointsStyles.js
- myApp/app/styles/constants.js
- myApp/app/styles/poiStyles.js
- myApp/app/styles/shuttlePopupStyles.js
- myApp/package-lock.json
- myApp/package.json
**Improvements:**
- Fix bug #279 
- Ensured events are displayed for a minimum of one month
- Improved UI for the calendar connection page
**New Features/Additions:**
- User now able to select how many months he would like to render the calendar for (1 month, 2 months,... 6 months or All)
- Unit tests for the new component
**Screenshots**
> Enhance calendar functionality: bug fix, month range selection, and UI improvements

- myApp/app/screens/CalendarSchedulePage.js
- myApp/app/styles/GoogleScheduleStyles.js
Following uggestions fro PO, we can now see what the next class is before getting directions to it. 
Change made after comments: Fallback UI for no upcoming class found
> Suggest the next class so user can see when & where it is before get directions

- myApp/app/(tabs)/map.jsx
Simply added the isDisabled Prop, was removed deleted from main somehow
To test try: H919 to H827
> Fix for disabled routes

- myApp/app/(tabs)/map.jsx
- myApp/app/components/Directions.tsx
- myApp/app/components/HeaderButtons.js
- myApp/app/components/IndoorMap/ShortestPathMap.js
- myApp/app/components/LayoutWrapper.js
- myApp/app/components/MapDirections.tsx
- myApp/app/components/MonthPicker.js
- myApp/app/components/ShuttleInfoPopup.jsx
- myApp/app/components/StartAndDestinationPoints.tsx
- myApp/app/context/LocationContext.tsx
- myApp/app/screens/CalendarFetching.js
- myApp/app/screens/CalendarSchedulePage.js
- myApp/app/screens/SettingsPage.js
- myApp/app/styles/CalendarFetchingStyles.js
- myApp/app/styles/GoogleScheduleStyles.js
- myApp/app/styles/InterestPointsStyles.js
- myApp/app/styles/OutdoorMapStyles.js
- myApp/app/styles/StartAndDestinationPointsStyles.js
This pull request includes code cleanup, refactoring, and adding PropTypes for better type checking. 
* Removed unused imports and variables from various files, including `map.jsx`, `Directions.tsx`, `HeaderButtons.js`, `LocationContext.tsx`, `CalendarFetching.js`, `CalendarSchedulePage.js`, and `SettingsPage.js`. [[1]](diffhunk://#diff-7676d412f0b71f728b7fd707c029fa360bee6acccf7c8978601f3ee486cc4f21L25-L26) [[2]](diffhunk://#diff-7676d412f0b71f728b7fd707c029fa360bee6acccf7c8978601f3ee486cc4f21L140) [[3]](diffhunk://#diff-7676d412f0b71f728b7fd707c029fa360bee6acccf7c8978601f3ee486cc4f21L824-L828) [[4]](diffhunk://#diff-9f9718852bbf795d1c697c59609d7049b6bbccffa5e91cca1fec1f0723552f73L1-L6) [[5]](diffhunk://#diff-21a3c12194e90449639d3f2aeec6997e8345af2b9fc1d31e5f4b9a7e8a3b53a2L1-R1) …
> Remove useless imports and var, duplicate var, and Added missing prop validation.

- myApp/app/__tests__/SmartNavigationInfoPage.test.js
Forgot to add the SmartNavigationInfoPage.test.js file in #349 pr
> add forgetten test file

- myApp/app/components/StartAndDestinationPoints.tsx
- myApp/app/styles/StartAndDestinationPointsStyles.js
This pull request introduces several changes to improve the indoor navigation feature in the `StartAndDestinationPoints` component.
Improvements to indoor navigation:
* [`myApp/app/components/StartAndDestinationPoints.tsx`](diffhunk://#diff-c24123e8dd55d10e485ab16073fe9610c8208992e96a7773935b44b77c517634R86): Added state `indoorNav` to manage indoor navigation and updated the component to show walking directions and indoor map path when indoor navigation is enabled. [[1]](diffhunk://#diff-c24123e8dd55d10e485ab16073fe9610c8208992e96a7773935b44b77c517634R86) [[2]](diffhunk://#diff-c24123e8dd55d10e485ab16073fe9610c8208992e96a7773935b44b77c517634R394-R399) [[3]](diffhunk://#diff-c24123e8dd55d10e485ab16073fe9610c8208992e96a7773935b44b77c517634R425-R434) …
> Integrate travel mode options with indoor maps

- myApp/app/(tabs)/_layout.tsx
- myApp/app/(tabs)/map.jsx
- myApp/app/__tests__/POITests/POIList.tests.js
- myApp/app/components/BuildingPopUp.tsx
- myApp/app/components/Directions.tsx
- myApp/app/components/IndoorMap/ShortestPath.js
- myApp/app/components/MapDirections.tsx
- myApp/app/screens/CalenderInfoPage.js
- myApp/app/screens/HomePage.js
- myApp/app/screens/InfoPage.js
- myApp/app/screens/PoiInfoPage.js
- myApp/app/styles/InfoPageStyles.js
- myApp/app/utils/shuttleUtils.js
Link fixed sonar issues here: 
Before: 
Current (still some left):
Acknowledged and choose to accept these: 
Justification for all 4 security issues: Due to the nature of the data being handled (available to the public, fetched via a public API), the use of Math.random() is sufficient here.
> Diverse SonarQube Fixes to improve Code Quality

- myApp/app/__tests__/POITests/POIList.tests.js
- myApp/app/components/POI/POIList.js
- myApp/app/utils/GooglePlacesProxy.js
This PR implements the Proxy design pattern through a new GooglePlacesProxy module to lazy load POI images.
GooglePlacesProxy.js: Caches image URLs and adds rate-limiting to reduce API load.
POIList.js: Replaces direct image loading with async fetch via the proxy.
Tests updated: Added support for "No Image Available" fallback and testID.
Improves performance, reduces redundant API calls, and decouples image loading logic from UI components.
> Proxy - Lazy Loading of Points of Interest with googlePlacesProxy

- map.jsx
- myApp/app/(tabs)/interest-points.jsx
- myApp/app/(tabs)/map.jsx
- myApp/app/__tests__/HomePage.tests.js
- myApp/app/components/Directions.tsx
- myApp/app/components/ShuttleInfoPopup.jsx
- myApp/app/components/StartAndDestinationPoints.tsx
- myApp/app/components/ThemeToggle.js
- myApp/app/context/ThemeContext.js
- myApp/app/index.js
- myApp/app/screens/CalendarFetching.js
- myApp/app/screens/CalendarSchedulePage.js
- myApp/app/screens/ShuttleScheduleScreen.js
- myApp/app/styles/POIListStyle.js
- myApp/app/utils/shuttleUtils.js
This PR addressed the remaining code smells and issues so that the quality gate passes.
> Final Code Quality Improvements
